//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_EF6_SP_3_tier_.Enitiies
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_id { get; set; }
        public string name { get; set; }
        public string cell { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
