//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_EF6_SP_3_tier_.Enitiies
{
    using System;
    using System.Collections.Generic;
    
    public partial class sell
    {
        public int trx_id { get; set; }
        public string prd_title { get; set; }
        public string prd_price { get; set; }
        public string prd_quantity { get; set; }
        public string prd_sell_date { get; set; }
        public string prd_sell_by { get; set; }
    }
}
